//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicReporterLib.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PublicReporterLib.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;110000&quot;]={&quot;code&quot;:&quot;110000&quot;,&quot;name&quot;:&quot;北京&quot;};	city[&quot;110000&quot;]=[	{&quot;code&quot;:&quot;110100&quot;,&quot;name&quot;:&quot;北京市&quot;}];county[&quot;110100&quot;]=[{&quot;code&quot;:&quot;110101&quot;,&quot;name&quot;:&quot;东城区&quot;},{&quot;code&quot;:&quot;110102&quot;,&quot;name&quot;:&quot;西城区&quot;},{&quot;code&quot;:&quot;110105&quot;,&quot;name&quot;:&quot;朝阳区&quot;},{&quot;code&quot;:&quot;110106&quot;,&quot;name&quot;:&quot;丰台区&quot;},{&quot;code&quot;:&quot;110107&quot;,&quot;name&quot;:&quot;石景山区&quot;},{&quot;code&quot;:&quot;110108&quot;,&quot;name&quot;:&quot;海淀区&quot;},{&quot;code&quot;:&quot;110109&quot;,&quot;name&quot;:&quot;门头沟区&quot;},{&quot;code&quot;:&quot;110111&quot;,&quot;name&quot;:&quot;房山区&quot;},{&quot;code&quot;:&quot;110112&quot;,&quot;name&quot;:&quot;通州区&quot;},{&quot;code&quot;:&quot;110113&quot;,&quot;name&quot;:&quot;顺义区&quot;},{&quot;code&quot;:&quot;110114&quot;,&quot;name&quot;:&quot;昌平区&quot;},{... 的本地化字符串。
        /// </summary>
        internal static string _110000 {
            get {
                return ResourceManager.GetString("_110000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;120000&quot;]={&quot;code&quot;:&quot;120000&quot;,&quot;name&quot;:&quot;天津&quot;};	city[&quot;120000&quot;]=[	{&quot;code&quot;:&quot;120100&quot;,&quot;name&quot;:&quot;天津市&quot;}];county[&quot;120100&quot;]=[{&quot;code&quot;:&quot;120101&quot;,&quot;name&quot;:&quot;和平区&quot;},{&quot;code&quot;:&quot;120102&quot;,&quot;name&quot;:&quot;河东区&quot;},{&quot;code&quot;:&quot;120103&quot;,&quot;name&quot;:&quot;河西区&quot;},{&quot;code&quot;:&quot;120104&quot;,&quot;name&quot;:&quot;南开区&quot;},{&quot;code&quot;:&quot;120105&quot;,&quot;name&quot;:&quot;河北区&quot;},{&quot;code&quot;:&quot;120106&quot;,&quot;name&quot;:&quot;红桥区&quot;},{&quot;code&quot;:&quot;120110&quot;,&quot;name&quot;:&quot;东丽区&quot;},{&quot;code&quot;:&quot;120111&quot;,&quot;name&quot;:&quot;西青区&quot;},{&quot;code&quot;:&quot;120112&quot;,&quot;name&quot;:&quot;津南区&quot;},{&quot;code&quot;:&quot;120113&quot;,&quot;name&quot;:&quot;北辰区&quot;},{&quot;code&quot;:&quot;120114&quot;,&quot;name&quot;:&quot;武清区&quot;},{&q... 的本地化字符串。
        /// </summary>
        internal static string _120000 {
            get {
                return ResourceManager.GetString("_120000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;130000&quot;]={&quot;code&quot;:&quot;130000&quot;,&quot;name&quot;:&quot;河北省&quot;};	city[&quot;130000&quot;]=[	{&quot;code&quot;:&quot;130100&quot;,&quot;name&quot;:&quot;石家庄市&quot;},{&quot;code&quot;:&quot;130200&quot;,&quot;name&quot;:&quot;唐山市&quot;},{&quot;code&quot;:&quot;130300&quot;,&quot;name&quot;:&quot;秦皇岛市&quot;},{&quot;code&quot;:&quot;130400&quot;,&quot;name&quot;:&quot;邯郸市&quot;},{&quot;code&quot;:&quot;130500&quot;,&quot;name&quot;:&quot;邢台市&quot;},{&quot;code&quot;:&quot;130600&quot;,&quot;name&quot;:&quot;保定市&quot;},{&quot;code&quot;:&quot;130700&quot;,&quot;name&quot;:&quot;张家口市&quot;},{&quot;code&quot;:&quot;130800&quot;,&quot;name&quot;:&quot;承德市&quot;},{&quot;code&quot;:&quot;130900&quot;,&quot;name&quot;:&quot;沧州市&quot;},{&quot;code&quot;:&quot;131000&quot;,&quot;name&quot;:&quot;廊坊市&quot;},{&quot;code&quot;:&quot;131100&quot;,&quot;name&quot;:&quot;衡水市&quot;}];county[&quot;130100&quot;]=[{&quot;code&quot;:&quot;130102&quot;,&quot;name&quot;:&quot;长安区&quot;}... 的本地化字符串。
        /// </summary>
        internal static string _130000 {
            get {
                return ResourceManager.GetString("_130000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;140000&quot;]={&quot;code&quot;:&quot;140000&quot;,&quot;name&quot;:&quot;山西省&quot;};	city[&quot;140000&quot;]=[	{&quot;code&quot;:&quot;140100&quot;,&quot;name&quot;:&quot;太原市&quot;},{&quot;code&quot;:&quot;140200&quot;,&quot;name&quot;:&quot;大同市&quot;},{&quot;code&quot;:&quot;140300&quot;,&quot;name&quot;:&quot;阳泉市&quot;},{&quot;code&quot;:&quot;140400&quot;,&quot;name&quot;:&quot;长治市&quot;},{&quot;code&quot;:&quot;140500&quot;,&quot;name&quot;:&quot;晋城市&quot;},{&quot;code&quot;:&quot;140600&quot;,&quot;name&quot;:&quot;朔州市&quot;},{&quot;code&quot;:&quot;140700&quot;,&quot;name&quot;:&quot;晋中市&quot;},{&quot;code&quot;:&quot;140800&quot;,&quot;name&quot;:&quot;运城市&quot;},{&quot;code&quot;:&quot;140900&quot;,&quot;name&quot;:&quot;忻州市&quot;},{&quot;code&quot;:&quot;141000&quot;,&quot;name&quot;:&quot;临汾市&quot;},{&quot;code&quot;:&quot;141100&quot;,&quot;name&quot;:&quot;吕梁市&quot;}];county[&quot;140100&quot;]=[{&quot;code&quot;:&quot;140105&quot;,&quot;name&quot;:&quot;小店区&quot;},{&... 的本地化字符串。
        /// </summary>
        internal static string _140000 {
            get {
                return ResourceManager.GetString("_140000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;150000&quot;]={&quot;code&quot;:&quot;150000&quot;,&quot;name&quot;:&quot;内蒙古自治区&quot;};	city[&quot;150000&quot;]=[	{&quot;code&quot;:&quot;150100&quot;,&quot;name&quot;:&quot;呼和浩特市&quot;},{&quot;code&quot;:&quot;150200&quot;,&quot;name&quot;:&quot;包头市&quot;},{&quot;code&quot;:&quot;150300&quot;,&quot;name&quot;:&quot;乌海市&quot;},{&quot;code&quot;:&quot;150400&quot;,&quot;name&quot;:&quot;赤峰市&quot;},{&quot;code&quot;:&quot;150500&quot;,&quot;name&quot;:&quot;通辽市&quot;},{&quot;code&quot;:&quot;150600&quot;,&quot;name&quot;:&quot;鄂尔多斯市&quot;},{&quot;code&quot;:&quot;150700&quot;,&quot;name&quot;:&quot;呼伦贝尔市&quot;},{&quot;code&quot;:&quot;150800&quot;,&quot;name&quot;:&quot;巴彦淖尔市&quot;},{&quot;code&quot;:&quot;150900&quot;,&quot;name&quot;:&quot;乌兰察布市&quot;},{&quot;code&quot;:&quot;152200&quot;,&quot;name&quot;:&quot;兴安盟&quot;},{&quot;code&quot;:&quot;152500&quot;,&quot;name&quot;:&quot;锡林郭勒盟&quot;},{&quot;code&quot;:&quot;152900&quot;,&quot;name&quot;:&quot;阿拉善盟&quot;}];county[&quot;1... 的本地化字符串。
        /// </summary>
        internal static string _150000 {
            get {
                return ResourceManager.GetString("_150000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;210000&quot;]={&quot;code&quot;:&quot;210000&quot;,&quot;name&quot;:&quot;辽宁省&quot;};	city[&quot;210000&quot;]=[	{&quot;code&quot;:&quot;210100&quot;,&quot;name&quot;:&quot;沈阳市&quot;},{&quot;code&quot;:&quot;210200&quot;,&quot;name&quot;:&quot;大连市&quot;},{&quot;code&quot;:&quot;210300&quot;,&quot;name&quot;:&quot;鞍山市&quot;},{&quot;code&quot;:&quot;210400&quot;,&quot;name&quot;:&quot;抚顺市&quot;},{&quot;code&quot;:&quot;210500&quot;,&quot;name&quot;:&quot;本溪市&quot;},{&quot;code&quot;:&quot;210600&quot;,&quot;name&quot;:&quot;丹东市&quot;},{&quot;code&quot;:&quot;210700&quot;,&quot;name&quot;:&quot;锦州市&quot;},{&quot;code&quot;:&quot;210800&quot;,&quot;name&quot;:&quot;营口市&quot;},{&quot;code&quot;:&quot;210900&quot;,&quot;name&quot;:&quot;阜新市&quot;},{&quot;code&quot;:&quot;211000&quot;,&quot;name&quot;:&quot;辽阳市&quot;},{&quot;code&quot;:&quot;211100&quot;,&quot;name&quot;:&quot;盘锦市&quot;},{&quot;code&quot;:&quot;211200&quot;,&quot;name&quot;:&quot;铁岭市&quot;},{&quot;code&quot;:&quot;211300&... 的本地化字符串。
        /// </summary>
        internal static string _210000 {
            get {
                return ResourceManager.GetString("_210000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;220000&quot;]={&quot;code&quot;:&quot;220000&quot;,&quot;name&quot;:&quot;吉林省&quot;};	city[&quot;220000&quot;]=[	{&quot;code&quot;:&quot;220100&quot;,&quot;name&quot;:&quot;长春市&quot;},{&quot;code&quot;:&quot;220200&quot;,&quot;name&quot;:&quot;吉林市&quot;},{&quot;code&quot;:&quot;220300&quot;,&quot;name&quot;:&quot;四平市&quot;},{&quot;code&quot;:&quot;220400&quot;,&quot;name&quot;:&quot;辽源市&quot;},{&quot;code&quot;:&quot;220500&quot;,&quot;name&quot;:&quot;通化市&quot;},{&quot;code&quot;:&quot;220600&quot;,&quot;name&quot;:&quot;白山市&quot;},{&quot;code&quot;:&quot;220700&quot;,&quot;name&quot;:&quot;松原市&quot;},{&quot;code&quot;:&quot;220800&quot;,&quot;name&quot;:&quot;白城市&quot;},{&quot;code&quot;:&quot;222400&quot;,&quot;name&quot;:&quot;延边朝鲜族自治州&quot;}];county[&quot;220100&quot;]=[{&quot;code&quot;:&quot;220102&quot;,&quot;name&quot;:&quot;南关区&quot;},{&quot;code&quot;:&quot;220103&quot;,&quot;name&quot;:&quot;宽城区&quot;},{&quot;code&quot;:&quot;220104&quot;,&quot;name&quot;:&quot;朝阳区&quot... 的本地化字符串。
        /// </summary>
        internal static string _220000 {
            get {
                return ResourceManager.GetString("_220000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;230000&quot;]={&quot;code&quot;:&quot;230000&quot;,&quot;name&quot;:&quot;黑龙江省&quot;};	city[&quot;230000&quot;]=[	{&quot;code&quot;:&quot;230100&quot;,&quot;name&quot;:&quot;哈尔滨市&quot;},{&quot;code&quot;:&quot;230200&quot;,&quot;name&quot;:&quot;齐齐哈尔市&quot;},{&quot;code&quot;:&quot;230300&quot;,&quot;name&quot;:&quot;鸡西市&quot;},{&quot;code&quot;:&quot;230400&quot;,&quot;name&quot;:&quot;鹤岗市&quot;},{&quot;code&quot;:&quot;230500&quot;,&quot;name&quot;:&quot;双鸭山市&quot;},{&quot;code&quot;:&quot;230600&quot;,&quot;name&quot;:&quot;大庆市&quot;},{&quot;code&quot;:&quot;230700&quot;,&quot;name&quot;:&quot;伊春市&quot;},{&quot;code&quot;:&quot;230800&quot;,&quot;name&quot;:&quot;佳木斯市&quot;},{&quot;code&quot;:&quot;230900&quot;,&quot;name&quot;:&quot;七台河市&quot;},{&quot;code&quot;:&quot;231000&quot;,&quot;name&quot;:&quot;牡丹江市&quot;},{&quot;code&quot;:&quot;231100&quot;,&quot;name&quot;:&quot;黑河市&quot;},{&quot;code&quot;:&quot;231200&quot;,&quot;name&quot;:&quot;绥化市&quot;},{&quot;code&quot;:&quot... 的本地化字符串。
        /// </summary>
        internal static string _230000 {
            get {
                return ResourceManager.GetString("_230000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;310000&quot;]={&quot;code&quot;:&quot;310000&quot;,&quot;name&quot;:&quot;上海&quot;};	city[&quot;310000&quot;]=[	{&quot;code&quot;:&quot;310100&quot;,&quot;name&quot;:&quot;上海市&quot;}];county[&quot;310100&quot;]=[{&quot;code&quot;:&quot;310101&quot;,&quot;name&quot;:&quot;黄浦区&quot;},{&quot;code&quot;:&quot;310104&quot;,&quot;name&quot;:&quot;徐汇区&quot;},{&quot;code&quot;:&quot;310105&quot;,&quot;name&quot;:&quot;长宁区&quot;},{&quot;code&quot;:&quot;310106&quot;,&quot;name&quot;:&quot;静安区&quot;},{&quot;code&quot;:&quot;310107&quot;,&quot;name&quot;:&quot;普陀区&quot;},{&quot;code&quot;:&quot;310108&quot;,&quot;name&quot;:&quot;闸北区&quot;},{&quot;code&quot;:&quot;310109&quot;,&quot;name&quot;:&quot;虹口区&quot;},{&quot;code&quot;:&quot;310110&quot;,&quot;name&quot;:&quot;杨浦区&quot;},{&quot;code&quot;:&quot;310112&quot;,&quot;name&quot;:&quot;闵行区&quot;},{&quot;code&quot;:&quot;310113&quot;,&quot;name&quot;:&quot;宝山区&quot;},{&quot;code&quot;:&quot;310114&quot;,&quot;name&quot;:&quot;嘉定区&quot;},{&q... 的本地化字符串。
        /// </summary>
        internal static string _310000 {
            get {
                return ResourceManager.GetString("_310000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;320000&quot;]={&quot;code&quot;:&quot;320000&quot;,&quot;name&quot;:&quot;江苏省&quot;};	city[&quot;320000&quot;]=[	{&quot;code&quot;:&quot;320100&quot;,&quot;name&quot;:&quot;南京市&quot;},{&quot;code&quot;:&quot;320200&quot;,&quot;name&quot;:&quot;无锡市&quot;},{&quot;code&quot;:&quot;320300&quot;,&quot;name&quot;:&quot;徐州市&quot;},{&quot;code&quot;:&quot;320400&quot;,&quot;name&quot;:&quot;常州市&quot;},{&quot;code&quot;:&quot;320500&quot;,&quot;name&quot;:&quot;苏州市&quot;},{&quot;code&quot;:&quot;320600&quot;,&quot;name&quot;:&quot;南通市&quot;},{&quot;code&quot;:&quot;320700&quot;,&quot;name&quot;:&quot;连云港市&quot;},{&quot;code&quot;:&quot;320800&quot;,&quot;name&quot;:&quot;淮安市&quot;},{&quot;code&quot;:&quot;320900&quot;,&quot;name&quot;:&quot;盐城市&quot;},{&quot;code&quot;:&quot;321000&quot;,&quot;name&quot;:&quot;扬州市&quot;},{&quot;code&quot;:&quot;321100&quot;,&quot;name&quot;:&quot;镇江市&quot;},{&quot;code&quot;:&quot;321200&quot;,&quot;name&quot;:&quot;泰州市&quot;},{&quot;code&quot;:&quot;321300... 的本地化字符串。
        /// </summary>
        internal static string _320000 {
            get {
                return ResourceManager.GetString("_320000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;330000&quot;]={&quot;code&quot;:&quot;330000&quot;,&quot;name&quot;:&quot;浙江省&quot;};	city[&quot;330000&quot;]=[	{&quot;code&quot;:&quot;330100&quot;,&quot;name&quot;:&quot;杭州市&quot;},{&quot;code&quot;:&quot;330200&quot;,&quot;name&quot;:&quot;宁波市&quot;},{&quot;code&quot;:&quot;330300&quot;,&quot;name&quot;:&quot;温州市&quot;},{&quot;code&quot;:&quot;330400&quot;,&quot;name&quot;:&quot;嘉兴市&quot;},{&quot;code&quot;:&quot;330500&quot;,&quot;name&quot;:&quot;湖州市&quot;},{&quot;code&quot;:&quot;330600&quot;,&quot;name&quot;:&quot;绍兴市&quot;},{&quot;code&quot;:&quot;330700&quot;,&quot;name&quot;:&quot;金华市&quot;},{&quot;code&quot;:&quot;330800&quot;,&quot;name&quot;:&quot;衢州市&quot;},{&quot;code&quot;:&quot;330900&quot;,&quot;name&quot;:&quot;舟山市&quot;},{&quot;code&quot;:&quot;331000&quot;,&quot;name&quot;:&quot;台州市&quot;},{&quot;code&quot;:&quot;331100&quot;,&quot;name&quot;:&quot;丽水市&quot;}];county[&quot;330100&quot;]=[{&quot;code&quot;:&quot;330102&quot;,&quot;name&quot;:&quot;上城区&quot;},{&... 的本地化字符串。
        /// </summary>
        internal static string _330000 {
            get {
                return ResourceManager.GetString("_330000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;340000&quot;]={&quot;code&quot;:&quot;340000&quot;,&quot;name&quot;:&quot;安徽省&quot;};	city[&quot;340000&quot;]=[	{&quot;code&quot;:&quot;340100&quot;,&quot;name&quot;:&quot;合肥市&quot;},{&quot;code&quot;:&quot;340200&quot;,&quot;name&quot;:&quot;芜湖市&quot;},{&quot;code&quot;:&quot;340300&quot;,&quot;name&quot;:&quot;蚌埠市&quot;},{&quot;code&quot;:&quot;340400&quot;,&quot;name&quot;:&quot;淮南市&quot;},{&quot;code&quot;:&quot;340500&quot;,&quot;name&quot;:&quot;马鞍山市&quot;},{&quot;code&quot;:&quot;340600&quot;,&quot;name&quot;:&quot;淮北市&quot;},{&quot;code&quot;:&quot;340700&quot;,&quot;name&quot;:&quot;铜陵市&quot;},{&quot;code&quot;:&quot;340800&quot;,&quot;name&quot;:&quot;安庆市&quot;},{&quot;code&quot;:&quot;341000&quot;,&quot;name&quot;:&quot;黄山市&quot;},{&quot;code&quot;:&quot;341100&quot;,&quot;name&quot;:&quot;滁州市&quot;},{&quot;code&quot;:&quot;341200&quot;,&quot;name&quot;:&quot;阜阳市&quot;},{&quot;code&quot;:&quot;341300&quot;,&quot;name&quot;:&quot;宿州市&quot;},{&quot;code&quot;:&quot;341500... 的本地化字符串。
        /// </summary>
        internal static string _340000 {
            get {
                return ResourceManager.GetString("_340000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;350000&quot;]={&quot;code&quot;:&quot;350000&quot;,&quot;name&quot;:&quot;福建省&quot;};	city[&quot;350000&quot;]=[	{&quot;code&quot;:&quot;350100&quot;,&quot;name&quot;:&quot;福州市&quot;},{&quot;code&quot;:&quot;350200&quot;,&quot;name&quot;:&quot;厦门市&quot;},{&quot;code&quot;:&quot;350300&quot;,&quot;name&quot;:&quot;莆田市&quot;},{&quot;code&quot;:&quot;350400&quot;,&quot;name&quot;:&quot;三明市&quot;},{&quot;code&quot;:&quot;350500&quot;,&quot;name&quot;:&quot;泉州市&quot;},{&quot;code&quot;:&quot;350600&quot;,&quot;name&quot;:&quot;漳州市&quot;},{&quot;code&quot;:&quot;350700&quot;,&quot;name&quot;:&quot;南平市&quot;},{&quot;code&quot;:&quot;350800&quot;,&quot;name&quot;:&quot;龙岩市&quot;},{&quot;code&quot;:&quot;350900&quot;,&quot;name&quot;:&quot;宁德市&quot;}];county[&quot;350100&quot;]=[{&quot;code&quot;:&quot;350102&quot;,&quot;name&quot;:&quot;鼓楼区&quot;},{&quot;code&quot;:&quot;350103&quot;,&quot;name&quot;:&quot;台江区&quot;},{&quot;code&quot;:&quot;350104&quot;,&quot;name&quot;:&quot;仓山区&quot;},{&... 的本地化字符串。
        /// </summary>
        internal static string _350000 {
            get {
                return ResourceManager.GetString("_350000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;360000&quot;]={&quot;code&quot;:&quot;360000&quot;,&quot;name&quot;:&quot;江西省&quot;};	city[&quot;360000&quot;]=[	{&quot;code&quot;:&quot;360100&quot;,&quot;name&quot;:&quot;南昌市&quot;},{&quot;code&quot;:&quot;360200&quot;,&quot;name&quot;:&quot;景德镇市&quot;},{&quot;code&quot;:&quot;360300&quot;,&quot;name&quot;:&quot;萍乡市&quot;},{&quot;code&quot;:&quot;360400&quot;,&quot;name&quot;:&quot;九江市&quot;},{&quot;code&quot;:&quot;360500&quot;,&quot;name&quot;:&quot;新余市&quot;},{&quot;code&quot;:&quot;360600&quot;,&quot;name&quot;:&quot;鹰潭市&quot;},{&quot;code&quot;:&quot;360700&quot;,&quot;name&quot;:&quot;赣州市&quot;},{&quot;code&quot;:&quot;360800&quot;,&quot;name&quot;:&quot;吉安市&quot;},{&quot;code&quot;:&quot;360900&quot;,&quot;name&quot;:&quot;宜春市&quot;},{&quot;code&quot;:&quot;361000&quot;,&quot;name&quot;:&quot;抚州市&quot;},{&quot;code&quot;:&quot;361100&quot;,&quot;name&quot;:&quot;上饶市&quot;}];county[&quot;360100&quot;]=[{&quot;code&quot;:&quot;360102&quot;,&quot;name&quot;:&quot;东湖区&quot;},{... 的本地化字符串。
        /// </summary>
        internal static string _360000 {
            get {
                return ResourceManager.GetString("_360000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;370000&quot;]={&quot;code&quot;:&quot;370000&quot;,&quot;name&quot;:&quot;山东省&quot;};	city[&quot;370000&quot;]=[	{&quot;code&quot;:&quot;370100&quot;,&quot;name&quot;:&quot;济南市&quot;},{&quot;code&quot;:&quot;370200&quot;,&quot;name&quot;:&quot;青岛市&quot;},{&quot;code&quot;:&quot;370300&quot;,&quot;name&quot;:&quot;淄博市&quot;},{&quot;code&quot;:&quot;370400&quot;,&quot;name&quot;:&quot;枣庄市&quot;},{&quot;code&quot;:&quot;370500&quot;,&quot;name&quot;:&quot;东营市&quot;},{&quot;code&quot;:&quot;370600&quot;,&quot;name&quot;:&quot;烟台市&quot;},{&quot;code&quot;:&quot;370700&quot;,&quot;name&quot;:&quot;潍坊市&quot;},{&quot;code&quot;:&quot;370800&quot;,&quot;name&quot;:&quot;济宁市&quot;},{&quot;code&quot;:&quot;370900&quot;,&quot;name&quot;:&quot;泰安市&quot;},{&quot;code&quot;:&quot;371000&quot;,&quot;name&quot;:&quot;威海市&quot;},{&quot;code&quot;:&quot;371100&quot;,&quot;name&quot;:&quot;日照市&quot;},{&quot;code&quot;:&quot;371200&quot;,&quot;name&quot;:&quot;莱芜市&quot;},{&quot;code&quot;:&quot;371300&... 的本地化字符串。
        /// </summary>
        internal static string _370000 {
            get {
                return ResourceManager.GetString("_370000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;410000&quot;]={&quot;code&quot;:&quot;410000&quot;,&quot;name&quot;:&quot;河南省&quot;};	city[&quot;410000&quot;]=[	{&quot;code&quot;:&quot;410100&quot;,&quot;name&quot;:&quot;郑州市&quot;},{&quot;code&quot;:&quot;410200&quot;,&quot;name&quot;:&quot;开封市&quot;},{&quot;code&quot;:&quot;410300&quot;,&quot;name&quot;:&quot;洛阳市&quot;},{&quot;code&quot;:&quot;410400&quot;,&quot;name&quot;:&quot;平顶山市&quot;},{&quot;code&quot;:&quot;410500&quot;,&quot;name&quot;:&quot;安阳市&quot;},{&quot;code&quot;:&quot;410600&quot;,&quot;name&quot;:&quot;鹤壁市&quot;},{&quot;code&quot;:&quot;410700&quot;,&quot;name&quot;:&quot;新乡市&quot;},{&quot;code&quot;:&quot;410800&quot;,&quot;name&quot;:&quot;焦作市&quot;},{&quot;code&quot;:&quot;410881&quot;,&quot;name&quot;:&quot;济源市&quot;},{&quot;code&quot;:&quot;410900&quot;,&quot;name&quot;:&quot;濮阳市&quot;},{&quot;code&quot;:&quot;411000&quot;,&quot;name&quot;:&quot;许昌市&quot;},{&quot;code&quot;:&quot;411100&quot;,&quot;name&quot;:&quot;漯河市&quot;},{&quot;code&quot;:&quot;411200... 的本地化字符串。
        /// </summary>
        internal static string _410000 {
            get {
                return ResourceManager.GetString("_410000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;420000&quot;]={&quot;code&quot;:&quot;420000&quot;,&quot;name&quot;:&quot;湖北省&quot;};	city[&quot;420000&quot;]=[	{&quot;code&quot;:&quot;420100&quot;,&quot;name&quot;:&quot;武汉市&quot;},{&quot;code&quot;:&quot;420200&quot;,&quot;name&quot;:&quot;黄石市&quot;},{&quot;code&quot;:&quot;420300&quot;,&quot;name&quot;:&quot;十堰市&quot;},{&quot;code&quot;:&quot;420500&quot;,&quot;name&quot;:&quot;宜昌市&quot;},{&quot;code&quot;:&quot;420600&quot;,&quot;name&quot;:&quot;襄阳市&quot;},{&quot;code&quot;:&quot;420700&quot;,&quot;name&quot;:&quot;鄂州市&quot;},{&quot;code&quot;:&quot;420800&quot;,&quot;name&quot;:&quot;荆门市&quot;},{&quot;code&quot;:&quot;420900&quot;,&quot;name&quot;:&quot;孝感市&quot;},{&quot;code&quot;:&quot;421000&quot;,&quot;name&quot;:&quot;荆州市&quot;},{&quot;code&quot;:&quot;421100&quot;,&quot;name&quot;:&quot;黄冈市&quot;},{&quot;code&quot;:&quot;421200&quot;,&quot;name&quot;:&quot;咸宁市&quot;},{&quot;code&quot;:&quot;421300&quot;,&quot;name&quot;:&quot;随州市&quot;},{&quot;code&quot;:&quot;422800&... 的本地化字符串。
        /// </summary>
        internal static string _420000 {
            get {
                return ResourceManager.GetString("_420000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;430000&quot;]={&quot;code&quot;:&quot;430000&quot;,&quot;name&quot;:&quot;湖南省&quot;};	city[&quot;430000&quot;]=[	{&quot;code&quot;:&quot;430100&quot;,&quot;name&quot;:&quot;长沙市&quot;},{&quot;code&quot;:&quot;430200&quot;,&quot;name&quot;:&quot;株洲市&quot;},{&quot;code&quot;:&quot;430300&quot;,&quot;name&quot;:&quot;湘潭市&quot;},{&quot;code&quot;:&quot;430400&quot;,&quot;name&quot;:&quot;衡阳市&quot;},{&quot;code&quot;:&quot;430500&quot;,&quot;name&quot;:&quot;邵阳市&quot;},{&quot;code&quot;:&quot;430600&quot;,&quot;name&quot;:&quot;岳阳市&quot;},{&quot;code&quot;:&quot;430700&quot;,&quot;name&quot;:&quot;常德市&quot;},{&quot;code&quot;:&quot;430800&quot;,&quot;name&quot;:&quot;张家界市&quot;},{&quot;code&quot;:&quot;430900&quot;,&quot;name&quot;:&quot;益阳市&quot;},{&quot;code&quot;:&quot;431000&quot;,&quot;name&quot;:&quot;郴州市&quot;},{&quot;code&quot;:&quot;431100&quot;,&quot;name&quot;:&quot;永州市&quot;},{&quot;code&quot;:&quot;431200&quot;,&quot;name&quot;:&quot;怀化市&quot;},{&quot;code&quot;:&quot;431300... 的本地化字符串。
        /// </summary>
        internal static string _430000 {
            get {
                return ResourceManager.GetString("_430000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;440000&quot;]={&quot;code&quot;:&quot;440000&quot;,&quot;name&quot;:&quot;广东省&quot;};	city[&quot;440000&quot;]=[	{&quot;code&quot;:&quot;440100&quot;,&quot;name&quot;:&quot;广州市&quot;},{&quot;code&quot;:&quot;440200&quot;,&quot;name&quot;:&quot;韶关市&quot;},{&quot;code&quot;:&quot;440300&quot;,&quot;name&quot;:&quot;深圳市&quot;},{&quot;code&quot;:&quot;440400&quot;,&quot;name&quot;:&quot;珠海市&quot;},{&quot;code&quot;:&quot;440500&quot;,&quot;name&quot;:&quot;汕头市&quot;},{&quot;code&quot;:&quot;440600&quot;,&quot;name&quot;:&quot;佛山市&quot;},{&quot;code&quot;:&quot;440700&quot;,&quot;name&quot;:&quot;江门市&quot;},{&quot;code&quot;:&quot;440800&quot;,&quot;name&quot;:&quot;湛江市&quot;},{&quot;code&quot;:&quot;440900&quot;,&quot;name&quot;:&quot;茂名市&quot;},{&quot;code&quot;:&quot;441200&quot;,&quot;name&quot;:&quot;肇庆市&quot;},{&quot;code&quot;:&quot;441300&quot;,&quot;name&quot;:&quot;惠州市&quot;},{&quot;code&quot;:&quot;441400&quot;,&quot;name&quot;:&quot;梅州市&quot;},{&quot;code&quot;:&quot;441500&... 的本地化字符串。
        /// </summary>
        internal static string _440000 {
            get {
                return ResourceManager.GetString("_440000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;450000&quot;]={&quot;code&quot;:&quot;450000&quot;,&quot;name&quot;:&quot;广西壮族自治区&quot;};	city[&quot;450000&quot;]=[	{&quot;code&quot;:&quot;450100&quot;,&quot;name&quot;:&quot;南宁市&quot;},{&quot;code&quot;:&quot;450200&quot;,&quot;name&quot;:&quot;柳州市&quot;},{&quot;code&quot;:&quot;450300&quot;,&quot;name&quot;:&quot;桂林市&quot;},{&quot;code&quot;:&quot;450400&quot;,&quot;name&quot;:&quot;梧州市&quot;},{&quot;code&quot;:&quot;450500&quot;,&quot;name&quot;:&quot;北海市&quot;},{&quot;code&quot;:&quot;450600&quot;,&quot;name&quot;:&quot;防城港市&quot;},{&quot;code&quot;:&quot;450700&quot;,&quot;name&quot;:&quot;钦州市&quot;},{&quot;code&quot;:&quot;450800&quot;,&quot;name&quot;:&quot;贵港市&quot;},{&quot;code&quot;:&quot;450900&quot;,&quot;name&quot;:&quot;玉林市&quot;},{&quot;code&quot;:&quot;451000&quot;,&quot;name&quot;:&quot;百色市&quot;},{&quot;code&quot;:&quot;451100&quot;,&quot;name&quot;:&quot;贺州市&quot;},{&quot;code&quot;:&quot;451200&quot;,&quot;name&quot;:&quot;河池市&quot;},{&quot;code&quot;:&quot;45... 的本地化字符串。
        /// </summary>
        internal static string _450000 {
            get {
                return ResourceManager.GetString("_450000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;460000&quot;]={&quot;code&quot;:&quot;460000&quot;,&quot;name&quot;:&quot;海南省&quot;};	city[&quot;460000&quot;]=[	{&quot;code&quot;:&quot;460100&quot;,&quot;name&quot;:&quot;海口市&quot;},{&quot;code&quot;:&quot;460200&quot;,&quot;name&quot;:&quot;三亚市&quot;},{&quot;code&quot;:&quot;460300&quot;,&quot;name&quot;:&quot;三沙市&quot;},{&quot;code&quot;:&quot;469001&quot;,&quot;name&quot;:&quot;五指山市&quot;},{&quot;code&quot;:&quot;469002&quot;,&quot;name&quot;:&quot;琼海市&quot;},{&quot;code&quot;:&quot;469003&quot;,&quot;name&quot;:&quot;儋州市&quot;},{&quot;code&quot;:&quot;469005&quot;,&quot;name&quot;:&quot;文昌市&quot;},{&quot;code&quot;:&quot;469006&quot;,&quot;name&quot;:&quot;万宁市&quot;},{&quot;code&quot;:&quot;469007&quot;,&quot;name&quot;:&quot;东方市&quot;},{&quot;code&quot;:&quot;469025&quot;,&quot;name&quot;:&quot;定安县&quot;},{&quot;code&quot;:&quot;469026&quot;,&quot;name&quot;:&quot;屯昌县&quot;},{&quot;code&quot;:&quot;469027&quot;,&quot;name&quot;:&quot;澄迈县&quot;},{&quot;code&quot;:&quot;469028... 的本地化字符串。
        /// </summary>
        internal static string _460000 {
            get {
                return ResourceManager.GetString("_460000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;500000&quot;]={&quot;code&quot;:&quot;500000&quot;,&quot;name&quot;:&quot;重庆&quot;};	city[&quot;500000&quot;]=[	{&quot;code&quot;:&quot;500100&quot;,&quot;name&quot;:&quot;重庆市&quot;}];county[&quot;500100&quot;]=[{&quot;code&quot;:&quot;500101&quot;,&quot;name&quot;:&quot;万州区&quot;},{&quot;code&quot;:&quot;500102&quot;,&quot;name&quot;:&quot;涪陵区&quot;},{&quot;code&quot;:&quot;500103&quot;,&quot;name&quot;:&quot;渝中区&quot;},{&quot;code&quot;:&quot;500104&quot;,&quot;name&quot;:&quot;大渡口区&quot;},{&quot;code&quot;:&quot;500105&quot;,&quot;name&quot;:&quot;江北区&quot;},{&quot;code&quot;:&quot;500106&quot;,&quot;name&quot;:&quot;沙坪坝区&quot;},{&quot;code&quot;:&quot;500107&quot;,&quot;name&quot;:&quot;九龙坡区&quot;},{&quot;code&quot;:&quot;500108&quot;,&quot;name&quot;:&quot;南岸区&quot;},{&quot;code&quot;:&quot;500109&quot;,&quot;name&quot;:&quot;北碚区&quot;},{&quot;code&quot;:&quot;500112&quot;,&quot;name&quot;:&quot;渝北区&quot;},{&quot;code&quot;:&quot;500113&quot;,&quot;name&quot;:&quot;巴南区&quot;},... 的本地化字符串。
        /// </summary>
        internal static string _500000 {
            get {
                return ResourceManager.GetString("_500000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;510000&quot;]={&quot;code&quot;:&quot;510000&quot;,&quot;name&quot;:&quot;四川省&quot;};	city[&quot;510000&quot;]=[	{&quot;code&quot;:&quot;510100&quot;,&quot;name&quot;:&quot;成都市&quot;},{&quot;code&quot;:&quot;510300&quot;,&quot;name&quot;:&quot;自贡市&quot;},{&quot;code&quot;:&quot;510400&quot;,&quot;name&quot;:&quot;攀枝花市&quot;},{&quot;code&quot;:&quot;510500&quot;,&quot;name&quot;:&quot;泸州市&quot;},{&quot;code&quot;:&quot;510600&quot;,&quot;name&quot;:&quot;德阳市&quot;},{&quot;code&quot;:&quot;510700&quot;,&quot;name&quot;:&quot;绵阳市&quot;},{&quot;code&quot;:&quot;510800&quot;,&quot;name&quot;:&quot;广元市&quot;},{&quot;code&quot;:&quot;510900&quot;,&quot;name&quot;:&quot;遂宁市&quot;},{&quot;code&quot;:&quot;511000&quot;,&quot;name&quot;:&quot;内江市&quot;},{&quot;code&quot;:&quot;511100&quot;,&quot;name&quot;:&quot;乐山市&quot;},{&quot;code&quot;:&quot;511300&quot;,&quot;name&quot;:&quot;南充市&quot;},{&quot;code&quot;:&quot;511400&quot;,&quot;name&quot;:&quot;眉山市&quot;},{&quot;code&quot;:&quot;511500... 的本地化字符串。
        /// </summary>
        internal static string _510000 {
            get {
                return ResourceManager.GetString("_510000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;520000&quot;]={&quot;code&quot;:&quot;520000&quot;,&quot;name&quot;:&quot;贵州省&quot;};	city[&quot;520000&quot;]=[	{&quot;code&quot;:&quot;520100&quot;,&quot;name&quot;:&quot;贵阳市&quot;},{&quot;code&quot;:&quot;520200&quot;,&quot;name&quot;:&quot;六盘水市&quot;},{&quot;code&quot;:&quot;520300&quot;,&quot;name&quot;:&quot;遵义市&quot;},{&quot;code&quot;:&quot;520400&quot;,&quot;name&quot;:&quot;安顺市&quot;},{&quot;code&quot;:&quot;522200&quot;,&quot;name&quot;:&quot;铜仁市&quot;},{&quot;code&quot;:&quot;522300&quot;,&quot;name&quot;:&quot;黔西南布依族苗族自治州&quot;},{&quot;code&quot;:&quot;522400&quot;,&quot;name&quot;:&quot;毕节市&quot;},{&quot;code&quot;:&quot;522600&quot;,&quot;name&quot;:&quot;黔东南苗族侗族自治州&quot;},{&quot;code&quot;:&quot;522700&quot;,&quot;name&quot;:&quot;黔南布依族苗族自治州&quot;}];county[&quot;520100&quot;]=[{&quot;code&quot;:&quot;520102&quot;,&quot;name&quot;:&quot;南明区&quot;},{&quot;code&quot;:&quot;520103&quot;,&quot;name&quot;:&quot;云岩区&quot;},{&quot;code&quot;:&quot;520111&quot;,&quot;name&qu... 的本地化字符串。
        /// </summary>
        internal static string _520000 {
            get {
                return ResourceManager.GetString("_520000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;530000&quot;]={&quot;code&quot;:&quot;530000&quot;,&quot;name&quot;:&quot;云南省&quot;};	city[&quot;530000&quot;]=[	{&quot;code&quot;:&quot;530100&quot;,&quot;name&quot;:&quot;昆明市&quot;},{&quot;code&quot;:&quot;530300&quot;,&quot;name&quot;:&quot;曲靖市&quot;},{&quot;code&quot;:&quot;530400&quot;,&quot;name&quot;:&quot;玉溪市&quot;},{&quot;code&quot;:&quot;530500&quot;,&quot;name&quot;:&quot;保山市&quot;},{&quot;code&quot;:&quot;530600&quot;,&quot;name&quot;:&quot;昭通市&quot;},{&quot;code&quot;:&quot;530700&quot;,&quot;name&quot;:&quot;丽江市&quot;},{&quot;code&quot;:&quot;530800&quot;,&quot;name&quot;:&quot;普洱市&quot;},{&quot;code&quot;:&quot;530900&quot;,&quot;name&quot;:&quot;临沧市&quot;},{&quot;code&quot;:&quot;532300&quot;,&quot;name&quot;:&quot;楚雄彝族自治州&quot;},{&quot;code&quot;:&quot;532500&quot;,&quot;name&quot;:&quot;红河哈尼族彝族自治州&quot;},{&quot;code&quot;:&quot;532600&quot;,&quot;name&quot;:&quot;文山壮族苗族自治州&quot;},{&quot;code&quot;:&quot;532800&quot;,&quot;name&quot;:&quot;西双版纳傣族自治州&quot;},{&quot;c... 的本地化字符串。
        /// </summary>
        internal static string _530000 {
            get {
                return ResourceManager.GetString("_530000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;540000&quot;]={&quot;code&quot;:&quot;540000&quot;,&quot;name&quot;:&quot;西藏自治区&quot;};	city[&quot;540000&quot;]=[	{&quot;code&quot;:&quot;540100&quot;,&quot;name&quot;:&quot;拉萨市&quot;},{&quot;code&quot;:&quot;542100&quot;,&quot;name&quot;:&quot;昌都地区&quot;},{&quot;code&quot;:&quot;542200&quot;,&quot;name&quot;:&quot;山南地区&quot;},{&quot;code&quot;:&quot;542300&quot;,&quot;name&quot;:&quot;日喀则地区&quot;},{&quot;code&quot;:&quot;542400&quot;,&quot;name&quot;:&quot;那曲地区&quot;},{&quot;code&quot;:&quot;542500&quot;,&quot;name&quot;:&quot;阿里地区&quot;},{&quot;code&quot;:&quot;542600&quot;,&quot;name&quot;:&quot;林芝地区&quot;}];county[&quot;540100&quot;]=[{&quot;code&quot;:&quot;540102&quot;,&quot;name&quot;:&quot;城关区&quot;},{&quot;code&quot;:&quot;540121&quot;,&quot;name&quot;:&quot;林周县&quot;},{&quot;code&quot;:&quot;540122&quot;,&quot;name&quot;:&quot;当雄县&quot;},{&quot;code&quot;:&quot;540123&quot;,&quot;name&quot;:&quot;尼木县&quot;},{&quot;code&quot;:&quot;540124&quot;,&quot;name&quot;:&quot;曲水县&... 的本地化字符串。
        /// </summary>
        internal static string _540000 {
            get {
                return ResourceManager.GetString("_540000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;610000&quot;]={&quot;code&quot;:&quot;610000&quot;,&quot;name&quot;:&quot;陕西省&quot;};	city[&quot;610000&quot;]=[	{&quot;code&quot;:&quot;610100&quot;,&quot;name&quot;:&quot;西安市&quot;},{&quot;code&quot;:&quot;610200&quot;,&quot;name&quot;:&quot;铜川市&quot;},{&quot;code&quot;:&quot;610300&quot;,&quot;name&quot;:&quot;宝鸡市&quot;},{&quot;code&quot;:&quot;610400&quot;,&quot;name&quot;:&quot;咸阳市&quot;},{&quot;code&quot;:&quot;610500&quot;,&quot;name&quot;:&quot;渭南市&quot;},{&quot;code&quot;:&quot;610600&quot;,&quot;name&quot;:&quot;延安市&quot;},{&quot;code&quot;:&quot;610700&quot;,&quot;name&quot;:&quot;汉中市&quot;},{&quot;code&quot;:&quot;610800&quot;,&quot;name&quot;:&quot;榆林市&quot;},{&quot;code&quot;:&quot;610900&quot;,&quot;name&quot;:&quot;安康市&quot;},{&quot;code&quot;:&quot;611000&quot;,&quot;name&quot;:&quot;商洛市&quot;}];county[&quot;610100&quot;]=[{&quot;code&quot;:&quot;610102&quot;,&quot;name&quot;:&quot;新城区&quot;},{&quot;code&quot;:&quot;610103&quot;,&quot;name&quot;:&quot;碑林区&quot;},{&... 的本地化字符串。
        /// </summary>
        internal static string _610000 {
            get {
                return ResourceManager.GetString("_610000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;620000&quot;]={&quot;code&quot;:&quot;620000&quot;,&quot;name&quot;:&quot;甘肃省&quot;};	city[&quot;620000&quot;]=[	{&quot;code&quot;:&quot;620100&quot;,&quot;name&quot;:&quot;兰州市&quot;},{&quot;code&quot;:&quot;620200&quot;,&quot;name&quot;:&quot;嘉峪关市&quot;},{&quot;code&quot;:&quot;620300&quot;,&quot;name&quot;:&quot;金昌市&quot;},{&quot;code&quot;:&quot;620400&quot;,&quot;name&quot;:&quot;白银市&quot;},{&quot;code&quot;:&quot;620500&quot;,&quot;name&quot;:&quot;天水市&quot;},{&quot;code&quot;:&quot;620600&quot;,&quot;name&quot;:&quot;武威市&quot;},{&quot;code&quot;:&quot;620700&quot;,&quot;name&quot;:&quot;张掖市&quot;},{&quot;code&quot;:&quot;620800&quot;,&quot;name&quot;:&quot;平凉市&quot;},{&quot;code&quot;:&quot;620900&quot;,&quot;name&quot;:&quot;酒泉市&quot;},{&quot;code&quot;:&quot;621000&quot;,&quot;name&quot;:&quot;庆阳市&quot;},{&quot;code&quot;:&quot;621100&quot;,&quot;name&quot;:&quot;定西市&quot;},{&quot;code&quot;:&quot;621200&quot;,&quot;name&quot;:&quot;陇南市&quot;},{&quot;code&quot;:&quot;622900... 的本地化字符串。
        /// </summary>
        internal static string _620000 {
            get {
                return ResourceManager.GetString("_620000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;630000&quot;]={&quot;code&quot;:&quot;630000&quot;,&quot;name&quot;:&quot;青海省&quot;};	city[&quot;630000&quot;]=[	{&quot;code&quot;:&quot;630100&quot;,&quot;name&quot;:&quot;西宁市&quot;},{&quot;code&quot;:&quot;632100&quot;,&quot;name&quot;:&quot;海东市&quot;},{&quot;code&quot;:&quot;632200&quot;,&quot;name&quot;:&quot;海北藏族自治州&quot;},{&quot;code&quot;:&quot;632300&quot;,&quot;name&quot;:&quot;黄南藏族自治州&quot;},{&quot;code&quot;:&quot;632500&quot;,&quot;name&quot;:&quot;海南藏族自治州&quot;},{&quot;code&quot;:&quot;632600&quot;,&quot;name&quot;:&quot;果洛藏族自治州&quot;},{&quot;code&quot;:&quot;632700&quot;,&quot;name&quot;:&quot;玉树藏族自治州&quot;},{&quot;code&quot;:&quot;632800&quot;,&quot;name&quot;:&quot;海西蒙古族藏族自治州&quot;}];county[&quot;630100&quot;]=[{&quot;code&quot;:&quot;630102&quot;,&quot;name&quot;:&quot;城东区&quot;},{&quot;code&quot;:&quot;630103&quot;,&quot;name&quot;:&quot;城中区&quot;},{&quot;code&quot;:&quot;630104&quot;,&quot;name&quot;:&quot;城西区&quot;},{&quot;code&quot;:&quot;630105&quot;,&quot;nam... 的本地化字符串。
        /// </summary>
        internal static string _630000 {
            get {
                return ResourceManager.GetString("_630000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;640000&quot;]={&quot;code&quot;:&quot;640000&quot;,&quot;name&quot;:&quot;宁夏回族自治区&quot;};	city[&quot;640000&quot;]=[	{&quot;code&quot;:&quot;640100&quot;,&quot;name&quot;:&quot;银川市&quot;},{&quot;code&quot;:&quot;640200&quot;,&quot;name&quot;:&quot;石嘴山市&quot;},{&quot;code&quot;:&quot;640300&quot;,&quot;name&quot;:&quot;吴忠市&quot;},{&quot;code&quot;:&quot;640400&quot;,&quot;name&quot;:&quot;固原市&quot;},{&quot;code&quot;:&quot;640500&quot;,&quot;name&quot;:&quot;中卫市&quot;}];county[&quot;640100&quot;]=[{&quot;code&quot;:&quot;640104&quot;,&quot;name&quot;:&quot;兴庆区&quot;},{&quot;code&quot;:&quot;640105&quot;,&quot;name&quot;:&quot;西夏区&quot;},{&quot;code&quot;:&quot;640106&quot;,&quot;name&quot;:&quot;金凤区&quot;},{&quot;code&quot;:&quot;640121&quot;,&quot;name&quot;:&quot;永宁县&quot;},{&quot;code&quot;:&quot;640122&quot;,&quot;name&quot;:&quot;贺兰县&quot;},{&quot;code&quot;:&quot;640181&quot;,&quot;name&quot;:&quot;灵武市&quot;}];county[&quot;640200&quot;]=[{&quot;code&quot;:&quot;640202&quot;,&q... 的本地化字符串。
        /// </summary>
        internal static string _640000 {
            get {
                return ResourceManager.GetString("_640000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;650000&quot;]={&quot;code&quot;:&quot;650000&quot;,&quot;name&quot;:&quot;新疆维吾尔自治区&quot;};	city[&quot;650000&quot;]=[	{&quot;code&quot;:&quot;650100&quot;,&quot;name&quot;:&quot;乌鲁木齐市&quot;},{&quot;code&quot;:&quot;650200&quot;,&quot;name&quot;:&quot;克拉玛依市&quot;},{&quot;code&quot;:&quot;652100&quot;,&quot;name&quot;:&quot;吐鲁番地区&quot;},{&quot;code&quot;:&quot;652200&quot;,&quot;name&quot;:&quot;哈密地区&quot;},{&quot;code&quot;:&quot;652300&quot;,&quot;name&quot;:&quot;昌吉回族自治州&quot;},{&quot;code&quot;:&quot;652700&quot;,&quot;name&quot;:&quot;博尔塔拉蒙古自治州&quot;},{&quot;code&quot;:&quot;652800&quot;,&quot;name&quot;:&quot;巴音郭楞蒙古自治州&quot;},{&quot;code&quot;:&quot;652900&quot;,&quot;name&quot;:&quot;阿克苏地区&quot;},{&quot;code&quot;:&quot;653000&quot;,&quot;name&quot;:&quot;克孜勒苏柯尔克孜自治州&quot;},{&quot;code&quot;:&quot;653100&quot;,&quot;name&quot;:&quot;喀什地区&quot;},{&quot;code&quot;:&quot;653200&quot;,&quot;name&quot;:&quot;和田地区&quot;},{&quot;code&quot;:&quot;654000&quot;,&quot;name&quot;:&quot;伊犁... 的本地化字符串。
        /// </summary>
        internal static string _650000 {
            get {
                return ResourceManager.GetString("_650000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;710000&quot;]={&quot;code&quot;:&quot;710000&quot;,&quot;name&quot;:&quot;台湾&quot;};	city[&quot;710000&quot;]=[	{&quot;code&quot;:&quot;710100&quot;,&quot;name&quot;:&quot;台北市&quot;},{&quot;code&quot;:&quot;710200&quot;,&quot;name&quot;:&quot;高雄市&quot;},{&quot;code&quot;:&quot;710300&quot;,&quot;name&quot;:&quot;台南市&quot;},{&quot;code&quot;:&quot;710400&quot;,&quot;name&quot;:&quot;台中市&quot;},{&quot;code&quot;:&quot;710500&quot;,&quot;name&quot;:&quot;金门县&quot;},{&quot;code&quot;:&quot;710600&quot;,&quot;name&quot;:&quot;南投县&quot;},{&quot;code&quot;:&quot;710700&quot;,&quot;name&quot;:&quot;基隆市&quot;},{&quot;code&quot;:&quot;710800&quot;,&quot;name&quot;:&quot;新竹市&quot;},{&quot;code&quot;:&quot;710900&quot;,&quot;name&quot;:&quot;嘉义市&quot;},{&quot;code&quot;:&quot;711100&quot;,&quot;name&quot;:&quot;新北市&quot;},{&quot;code&quot;:&quot;711200&quot;,&quot;name&quot;:&quot;宜兰县&quot;},{&quot;code&quot;:&quot;711300&quot;,&quot;name&quot;:&quot;新竹县&quot;},{&quot;code&quot;:&quot;711400&q... 的本地化字符串。
        /// </summary>
        internal static string _710000 {
            get {
                return ResourceManager.GetString("_710000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;810000&quot;]={&quot;code&quot;:&quot;810000&quot;,&quot;name&quot;:&quot;香港特别行政区&quot;};	city[&quot;810000&quot;]=[	{&quot;code&quot;:&quot;810100&quot;,&quot;name&quot;:&quot;香港岛&quot;},{&quot;code&quot;:&quot;810200&quot;,&quot;name&quot;:&quot;九龙&quot;},{&quot;code&quot;:&quot;810300&quot;,&quot;name&quot;:&quot;新界&quot;}];county[&quot;810100&quot;]=[{&quot;code&quot;:&quot;810101&quot;,&quot;name&quot;:&quot;中西区&quot;},{&quot;code&quot;:&quot;810102&quot;,&quot;name&quot;:&quot;湾仔&quot;},{&quot;code&quot;:&quot;810103&quot;,&quot;name&quot;:&quot;东区&quot;},{&quot;code&quot;:&quot;810104&quot;,&quot;name&quot;:&quot;南区&quot;}];county[&quot;810200&quot;]=[{&quot;code&quot;:&quot;810201&quot;,&quot;name&quot;:&quot;九龙城区&quot;},{&quot;code&quot;:&quot;810202&quot;,&quot;name&quot;:&quot;油尖旺区&quot;},{&quot;code&quot;:&quot;810203&quot;,&quot;name&quot;:&quot;深水埗区&quot;},{&quot;code&quot;:&quot;810204&quot;,&quot;name&quot;:&quot;黄大仙区&quot;},{&quot;code&quot;:&quot;810205&quot;,&quo... 的本地化字符串。
        /// </summary>
        internal static string _810000 {
            get {
                return ResourceManager.GetString("_810000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///provice[&quot;820000&quot;]={&quot;code&quot;:&quot;820000&quot;,&quot;name&quot;:&quot;澳门特别行政区&quot;};	city[&quot;820000&quot;]=[	{&quot;code&quot;:&quot;820100&quot;,&quot;name&quot;:&quot;澳门半岛&quot;},{&quot;code&quot;:&quot;820200&quot;,&quot;name&quot;:&quot;离岛&quot;}];	 的本地化字符串。
        /// </summary>
        internal static string _820000 {
            get {
                return ResourceManager.GetString("_820000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;110000&quot;: &quot;北京&quot;,
        ///	&quot;120000&quot;: &quot;天津&quot;,
        ///	&quot;130000&quot;: &quot;河北省&quot;,
        ///	&quot;140000&quot;: &quot;山西省&quot;,
        ///	&quot;150000&quot;: &quot;内蒙古自治区&quot;,
        ///	&quot;210000&quot;: &quot;辽宁省&quot;,
        ///	&quot;220000&quot;: &quot;吉林省&quot;,
        ///	&quot;230000&quot;: &quot;黑龙江省&quot;,
        ///	&quot;310000&quot;: &quot;上海&quot;,
        ///	&quot;320000&quot;: &quot;江苏省&quot;,
        ///	&quot;330000&quot;: &quot;浙江省&quot;,
        ///	&quot;340000&quot;: &quot;安徽省&quot;,
        ///	&quot;350000&quot;: &quot;福建省&quot;,
        ///	&quot;360000&quot;: &quot;江西省&quot;,
        ///	&quot;370000&quot;: &quot;山东省&quot;,
        ///	&quot;410000&quot;: &quot;河南省&quot;,
        ///	&quot;420000&quot;: &quot;湖北省&quot;,
        ///	&quot;430000&quot;: &quot;湖南省&quot;,
        ///	&quot;440000&quot;: &quot;广东省&quot;,
        ///	&quot;450000&quot;: &quot;广西壮族自治区&quot;,
        ///	&quot;460000&quot;: &quot;海南省&quot;,
        ///	&quot;500000&quot;: &quot;重庆&quot;,
        ///	&quot;510000&quot;: &quot;四川省&quot;,
        ///	&quot;520000&quot;: &quot;贵州省&quot;,
        ///	&quot;530000&quot;: &quot;云南省&quot;,
        ///	&quot;540000&quot;: &quot;西藏自治区&quo... 的本地化字符串。
        /// </summary>
        internal static string _province {
            get {
                return ResourceManager.GetString("_province", resourceCulture);
            }
        }
    }
}
